require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'rdoc/task'
require 'sms_sender'

# Default to validation
task default: :validate

# Testing framework
RSpec::Core::RakeTask.new(:spec)

# Linter
RuboCop::RakeTask.new(:rubocop) do |task|
  task.options = ['-D']
end

namespace :test do
  RSpec::Core::RakeTask.new(:spec) do
  end
end

namespace :test do
  ##
  # sends a real message over the API to James' phone
  task :acceptance do
    ExampleSender.new.send('0400400269', 'Heatwave acceptance tests')
    ExampleSender.new.send_many(['0400400269','0400400269'],
                                'Heatwave acceptance tests - multiple texts')
  end
end

task test: :spec # Run all tests for this gem.

# Validation runs tests and the linter.
task validate: :test
task validate: :rubocop

# Rdoc produces documentation for this gem.
RDoc::Task.new :rdoc do |task|
  task.main = 'README.md'
  task.rdoc_files.include('README.md', 'lib/**/*.rb')
end
