#!/bin/bash
bold='\e[1;36m'
info='\e[0;36m'
error='\e[1;31m'
NC='\e[0m'

echo -e "\
${info}Note: this script assumes the components have been installed
with the install script first.$NC\
"

# The secret key needs to be set for production mode.
# It is used for validating cookies for sessions, etc.
# It can be changed freely but doing so will invalidate cookies
# (such as for saved sessions).
SECRET_KEY_BASE='fGz3zN7bxjukXksoG8olIneU4F0YN0R0nXIo3M0660FI8fV BuF6eVDyRDCyaAuyY'\
'0ElxZvrXFC8vbKIXyMrptKoWJhxYDZO9XUuy4JhtN 9JuoWzjbOPY8UhfBf8ZPwSt'
echo -e "${info}SECRET_KEY_BASE = [HIDDEN]$NC"

# This is required for the server to be able to accept connections
# over the network.
BINDING_ADDRESS='0.0.0.0'
echo -e "${info}BINDING_ADDRESS = ${BINDING_ADDRESS}${NC}"

# This should be changed to a different port in production,
# depending on the runtime server environment.
PORT=3000
echo -e "${info}PORT = ${PORT}$NC"

# Set Ruby path
if [[ -z "$WD" ]]; then
    echo
    echo -e "${bold}Setting rubygems home${NC}"
    if [[ "$(type ruby)" ]]; then
        PATH="$PATH:$(ruby -rubygems -e 'puts Gem.user_dir')/bin"
    fi
    export GEM_HOME="$(ruby -rubygems -e 'puts Gem.user_dir')"
    echo
    echo -e "${info}GEM_HOME=$GEM_HOME${NC}"
fi

# Configure paths.

export RAILS_HOME="$PWD/heatwave"
export PULLER_HOME="$PWD/puller"
export MESSENGER_HOME="$PWD/messenger"
export SENDER_HOME="$PWD/sms_sender"

echo
echo -e "${bold}Loading configuration${NC}"
if [[ -e ~/.heatwave.conf ]]; then
    echo -e "${info}from $HOME/.heatwave.conf${NC}"
    source "$HOME/.heatwave.conf"
elif [[ -e /usr/local/etc/heatwave.conf ]]; then
    echo -e "${info}from /usr/local/etc/.heatwave.conf${NC}"
    source /usr/local/etc/heatwave.conf
elif [[ -e /usr/etc/heatwave.conf ]]; then
    echo -e "${info}from /usr/etc/.heatwave.conf${NC}"
    source /usr/etc/heatwave.conf
elif [[ -e /etc/heatwave.conf ]]; then
    echo -e "${info}from /etc/.heatwave.conf${NC}"
    source /etc/heatwave.conf
else
    echo -e "using defaults relative to ${PWD}${NC}"
fi

echo -e "${info}RAILS_HOME=${RAILS_HOME}${NC}"
echo -e "${info}PULLER_HOME=${PULLER_HOME}${NC}"
echo -e "${info}MESSENGER_HOME=${MESSENGER_HOME}${NC}"
echo -e "${info}SENDER_HOME=${SENDER_HOME}${NC}"

# Configure database

export RAILS_ENV=production
echo -e "${info}RAILS_ENV=${RAILS_ENV}${NC}"
export DATABASE_ENV=production
echo -e "${info}DATABASE_ENV=${DATABASE_ENV}${NC}"

# Set up components.

echo
echo -e "${bold}Running the Heatwave rails application...${NC}"
cd "$RAILS_HOME"

SECRET_KEY_BASE=$SECRET_KEY_BASE bundle exec rails s -b $BINDING_ADDRESS -p $PORT
