#!/usr/bin/env ruby

require 'puller'

source = { hostname: 'ftp2.bom.gov.au',
           filename: '/anon/gen/fwo/IDA00003.dat',
           user: 'ftp',
           passwd: '' }

Puller::Database.initialise
Puller::ModelMarshaler.weather_model = Weather
Puller::ModelMarshaler.location_model = Location

pipeline = { getter: Puller::Getter,
             processor: Puller::Processor,
             marshaler: Puller::ModelMarshaler }

puts "Added #{Puller.pull_from(source, pipeline)} records."
