#!/usr/bin/env ruby

require 'puller'

HOSTNAME = 'ftp2.bom.gov.au'
FILENAME = '/anon/gen/fwo/IDA00003.dat'
USER = 'ftp'
PASSWD = ''

source = { hostname: 'ftp2.bom.gov.au',
           filename: '/anon/gen/fwo/IDA00003.dat',
           user: 'ftp',
           passwd: '' }

pipeline = { getter: Puller::Getter,
             processor: Puller::Processor,
             marshaller: Marshal }

puts Puller.pull_from(source, pipeline)
